name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 8
    - uses: coursier/setup-action@v1
      with:
        apps: sbt
    - uses: coursier/cache-action@v6
    - name: test
      run: sbt +test scripted mimaReportBinaryIssues
