name: Publish

on:
  push:
    branches: # Snapshots
      - main
    tags: ["**"] # Releases
  release:
    types: [published]

jobs:
  publish-artifacts:
    runs-on: ubuntu-22.04
    if: ${{ github.repository_owner == 'sbt' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1
        with:
          apps: sbt
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      - name: Publish artifacts
        run: sbt ci-release
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
